const BusinessInformationForm = [
    {
        id: 'type_entity',
        label: 'Type of Entity',
        options: [
            {hasChildren: false, value: 'Company'},
            {hasChildren: false, value: 'LLC'},
            {hasChildren: false, value: 'Colombia'},
            {hasChildren: false, value: 'Corporation'},
            {hasChildren: false, value: 'S-Corp'},
            {hasChildren: false, value: 'Trust'},

        ],
        errorId: 'type_entity_error_id',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'entity_name',
        label: 'Entity name',
        errorId: 'entity_name_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [
            {
                validation: /^(?!.*([A-Za-zñÑáéíóúÁÉÍÓÚ\s])\1{3}).+$/,
                errorText: 'Incluye tu nombre completo, tal como aparece en tu identificación'
            },
            {
                validation: /^[A-Za-z][A-Za-z]*$/,
                errorText: 'Incluye tu nombre completo, tal como aparece en tu identificación'
            }

        ],
        maxLength: 200,
        minLength: 5,
        isRequired: true,
    },
    {
        id: 'signature',
        label: 'Authorized Signature ( First name + Last)',
        errorId: 'signature_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 200,
        minLength: 5,
        isRequired: true,
    },
    {
        id: 'tax_country',
        label: 'Please enter account owner Tax Country',
        options: [
            {hasChildren: false, label:'Select country', value: 0},
            {
                hasChildren:  {
                    id: 'tax_id',
                    label: 'Please enter the account owner Tax ID # without any dashes',
                    errorId: 'tax_id_error',
                    placeholder: '',
                    typeInput: 'textField',
                    type: 'number',
                    placeholder: 'Enter social security number here',
                    maxLength: 9, 
                    minLength: 9,
                    isRequired: true,
                    parentOf: 'United States',
                    validationRegex: [{ 
                        validation: /(.*[a-z0-9]){2}/i,
                        errorText: 'State needs to be min 2 characters'
                    }],
                },
                value:'United States',
            },
            {
                hasChildren:  {
                    id: 'tax_id',
                    label: 'Please enter the account owner Tax ID # without any dashes',
                    errorId: 'tax_id_error',
                    placeholder: '',
                    typeInput: 'textField',
                    maxLength: 12, 
                    minLength: 12,
                    placeholder: 'Enter RIF here',
                    isRequired: true,
                    parentOf: 'Venezuela',
                    validationRegex: [{ 
                        validation: /(.*[a-z0-9]){2}/i,
                        errorText: 'State needs to be min 2 characters'
                    }],
                },
                value:'Venezuela',
            },
            {
                hasChildren:  {
                    id: 'tax_id',
                    label: 'Please enter the account owner Tax ID # without any dashes',
                    errorId: 'tax_id_error',
                    placeholder: '',
                    typeInput: 'textField',
                    maxLength: 9,
                    minLength: 8,
                    placeholder: 'Enter RUT here',
                    parentOf: 'Colombia',
                    isRequired: true,
                    validationRegex: [{ 
                        validation: /(.*[a-z0-9]){2}/i,
                        errorText: 'State needs to be min 2 characters'
                    }],
                },
                value:'Colombia',
            },
            {
                hasChildren:  {
                    id: 'tax_id',
                    label: 'Please enter the account owner Tax ID # without any dashes',
                    errorId: 'tax_id_error',
                    placeholder: 'Enter CUIT/CUIL here',
                    typeInput: 'textField',
                    type:'number',
                    maxLength: 9, //SSN has 9 digits
                    minLength: 8,
                    isRequired: true,
                    parentOf:'Argentina',
                    validationRegex: [{ 
                        validation: /(.*[a-z0-9]){2}/i,
                        errorText: 'State needs to be min 2 characters'
                    }],
                },
                value:'Argentina',
            },
            {
                hasChildren:  {
                    id: 'tax_id',
                    label: 'Please enter the account owner Tax ID # without any dashes',
                    errorId: 'tax_id_error',
                    placeholder: 'Enter RUC here',
                    typeInput: 'textField',
                    type:'number',
                    maxLength: 11,
                    minLength: 7,
                    isRequired: true,
                    parentOf:'Panama',
                    validationRegex: [{ 
                        validation: /(.*[a-z0-9]){2}/i,
                        errorText: 'State needs to be min 2 characters'
                    }],
                },
                value:'Panama',
            },
        ],
        errorId: 'tax_country_error',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'tax_id_document',
        label: 'Tax ID Document',
        errorId: 'tax_id_document_error',
        placeholder: '',
        typeInput: 'FileUpload',
        fileUploaded: null,
        isRequired: true,
    },
    {
        id: 'region_formation',
        label: 'Region of Formation',
        options: ['no idea where search this info',],
        errorId: 'region_formation_error',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'phone_number',
        label: 'Please enter the account owners number including country code',
        errorId: 'phone_number_error',
        placeholder: 'Phone number',
        typeInput: 'textField',
        validationRegex: [
            {
                validation: /^[0-9]*$/,
                errorText: 'Please remove special characters +()- etc'
            },
        ],
        maxLength: 200,
        minLength: 5,
        isRequired: true,
    },
    {
        id: 'document_shareholders',
        label: 'Document of list of shareholders',
        errorId: 'document_shareholders_error',
        placeholder: '',
        typeInput: 'FileUpload',
        fileUploaded: null,
        isRequired: true,
    },
    {
        id: 'part?',
        label: 'Everyone who has more that 25% of business uploads Shareholders info ***copy personal info from other form but add two fields: Company role and email Must include proof of ID and Proof of address along with uploads',
        errorId: 'part?',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 200,
        minLength: 2,
        isRequired: true,
    },
    {
        id: 'company_role',
        label: 'Company Role',
        errorId: 'company_role_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 200,
        minLength: 2,
        isRequired: true,
    },
    {
        id: 'shareholder_email',
        label: 'Shareholder Email',
        errorId: 'shareholder_email_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [{
            validation: /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/,
            errorText: 'Please enter a valid email'
    }],
        maxLength: 200,
        minLength: 2,
        isRequired: true,
    },
    {
        id: 'company_street',
        label: 'Company Street',
        errorId: 'company_street_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 200,
        minLength: 2,
        isRequired: true,
    },
    {
        id: 'company_street_2',
        label: 'Company Street 2',
        errorId: 'company_street_2error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 200,
        minLength: 2,
        isRequired: false,
    },
    {
        id: 'country_selection',
        hasChildren: 'state_related_selection',
        label: 'Company Country',
        options: [
            {hasChildren: false, label:'Select country', value: 0},
            {hasChildren: {
                id: 'state_related_selection',
                label: 'Company State',
                options: [
                    {hasChildren:false, label: 'Select State', value: 0},
                    {hasChildren:false, label: 'Alabama', value: 'AL'},
                    {hasChildren:false, label: 'Alaska', value: 'AK'},
                    {hasChildren:false, label: 'Arizona', value: 'AZ'},
                    {hasChildren:false, label: 'Arkansas', value: 'AR'},
                    {hasChildren:false, label: 'California', value: 'CA'},
                    {hasChildren:false, label: 'Colorado', value: 'CO'},
                    {hasChildren:false, label: 'Connectiacut', value: 'CT'},
                    {hasChildren:false, label: 'Delaware', value: 'DE'},
                    {hasChildren:false, label: 'Florida', value: 'FL'},
                    {hasChildren:false, label: 'Georgia', value: 'GA'},
                    {hasChildren:false, label: 'Hawaii', value: 'HI'},
                    {hasChildren:false, label: 'Idaho', value: 'ID'},
                    {hasChildren:false, label: 'Illinois', value: 'IL'},
                    {hasChildren:false, label: 'Indiana', value: 'IN'},
                    {hasChildren:false, label: 'Iowa', value: 'IA'},
                    {hasChildren:false, label: 'Kansas', value: 'KS'},
                    {hasChildren:false, label: 'Kentuky', value: 'KY'},
                    {hasChildren:false, label: 'Louisiana', value: 'LA'},
                    {hasChildren:false, label: 'Maine', value: 'ME'},
                    {hasChildren:false, label: 'Maryland', value: 'MD'},
                    {hasChildren:false, label: 'Massachusetts', value: 'MA'},
                    {hasChildren:false, label: 'Michigan', value: 'MI'},
                    {hasChildren:false, label: 'Minnesota', value: 'MN'},
                    {hasChildren:false, label: 'Mississippi', value: 'MS'},
                    {hasChildren:false, label: 'Missouri', value: 'MO'},
                    {hasChildren:false, label: 'Montana', value: 'MT'},
                    {hasChildren:false, label: 'Nebraska', value: 'NE'},
                    {hasChildren:false, label: 'Nevada', value: 'NV'},
                    {hasChildren:false, label: 'New Hampshire', value: 'NH'},
                    {hasChildren:false, label: 'New Jersey', value: 'NJ'},
                    {hasChildren:false, label: 'New Mexico', value: 'NM'},
                    {hasChildren:false, label: 'New York', value: 'NY'},
                    {hasChildren:false, label: 'North Carolina', value: 'NC'},
                    {hasChildren:false, label: 'North Dakota', value: 'ND'},
                    {hasChildren:false, label: 'Ohio', value: 'OH'},
                    {hasChildren:false, label: 'Oklahoma', value: 'OK'},
                    {hasChildren:false, label: 'Oregon', value: 'OR'},
                    {hasChildren:false, label: 'PennsyIvania', value: 'PA'},
                    {hasChildren:false, label: 'Rhode Island', value: 'RI'},
                    {hasChildren:false, label: 'South Carolina', value: 'SC'},
                    {hasChildren:false, label: 'South Dakota', value: 'SD'},
                    {hasChildren:false, label: 'Tennessee', value: 'TN'},
                    {hasChildren:false, label: 'Texas', value: 'TX'},
                    {hasChildren:false, label: 'Utah', value: 'UT'},
                    {hasChildren:false, label: 'Vermont', value: 'VT'},
                    {hasChildren:false, label: 'Virginia', value: 'VA'},
                    {hasChildren:false, label: 'Washington', value: 'WA'},
                    {hasChildren:false, label: 'West Virginia', value: 'WV'},
                    {hasChildren:false, label: 'Wisconsin', value: 'WI'},
                    {hasChildren:false, label: 'Wyoming', value: 'WY'},
                ], 
                errorId: 'state_related_error',
                placeholder: '',
                typeInput: 'Dropdown',
                isRequired: true,
                parentOf: 'United States',
            }, value:'United States', label: 'United States'},
            {hasChildren: 
                {
                    id: 'state_related_selection',
                    label: 'Company State',
                    errorId: 'state_related_selection_error',
                    placeholder: '',
                    typeInput: 'textField',
                    validationRegex: [{ 
                        validation: /(.*[a-z0-9]){2}/i,
                        errorText: 'State needs to be min 2 characters'
                    }],
                    maxLength: 50,
                    minLength: 2,
                    parentOf: 'Venezuela',
                    isRequired: true,
                },
                value:'Venezuela',
                label: 'Venezuela'
            },
            {hasChildren: 
                {
                    id: 'state_related_selection',
                    label: 'Company State',
                    errorId: 'state_related_selection_error',
                    placeholder: '',
                    typeInput: 'textField',
                    validationRegex: [{ 
                        validation: /(.*[a-z0-9]){2}/i,
                        errorText: 'State needs to be min 2 characters'
                    }],
                    maxLength: 50,
                    minLength: 2,
                    isRequired: true,
                    parentOf: 'Colombia',
                },
                value:'Colombia',
                label: 'Colombia'
            },
            {hasChildren: 
                {
                    id: 'state_related_selection',
                    label: 'Company State',
                    errorId: 'state_related_selection_error',
                    placeholder: '',
                    typeInput: 'textField',
                    validationRegex: [{ 
                        validation: /(.*[a-z0-9]){2}/i,
                        errorText: 'State needs to be min 2 characters'
                    }],
                    maxLength: 50,
                    minLength: 2,
                    isRequired: true,
                    parentOf: 'Argentina',
                },
                value:'Argentina',
                label: 'Argentina'
            },
            {hasChildren: 
                {
                    id: 'state_related_selection',
                    label: 'Company State',
                    errorId: 'state_related_selection_error',
                    placeholder: '',
                    typeInput: 'textField',
                    validationRegex: [{ 
                        validation: /(.*[a-z0-9]){2}/i,
                        errorText: 'State needs to be min 2 characters'
                    }],
                    maxLength: 50,
                    minLength: 2,
                    isRequired: true,
                    parentOf: 'Panama',
                },
                value:'Panama',
                label: 'Panama'
            },
        ],
        errorId: 'country_error',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'company_city_related',
        label: 'Company City',
        errorId: 'company_city_related_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [{ 
            validation: /(.*[a-z0-9]){2}/i,
            errorText: 'City needs to be min 2 characters'
        }],
        maxLength: 50,
        minLength: 2,
        isRequired: true,
    },
    {
        id: 'company_postal_code',
        label: 'Company Postal Code',
        errorId: 'postal_code_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 50,
        minLength: 2,
        isRequired: true,
    },
    {
        id: 'document_creation',
        label: 'Document Creation of Business',
        errorId: 'document_creation_error',
        placeholder: '',
        typeInput: 'FileUpload',
        fileUploaded: null,
        isRequired: true,
    },
    {
        id: 'validate_addres_type',
        label: 'Validate address document type',
        options: ['?'],
        errorId: 'validate_addres_type_error',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'validate_address_document',
        label: 'Validate Address Document',
        errorId: 'validate_address_document_error',
        placeholder: '',
        typeInput: 'FileUpload',
        fileUploaded: null,
        isRequired: true,
    },
    {
        id: 'reference_account_name',
        label: 'Reference account name and number',
        errorId: 'reference_account_name_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [
            {
                validation: /^(?!.*([A-Za-zñÑáéíóúÁÉÍÓÚ\s])\1{3}).+$/,
                errorText: 'Incluye tu nombre completo, tal como aparece en tu identificación'
            },
            {
                validation: /^[A-Za-z][A-Za-z]*$/,
                errorText: 'Incluye tu nombre completo, tal como aparece en tu identificación'
            }

        ],
        maxLength: 200,
        minLength: 5,
        isRequired: true,
    },
]