const BusinessInformationForm = [
    {
        id: 'type_entity',
        label: 'Type of Entity',
        options: ['Company', 'LLC', 'Colombia', 'Corporation', 'S-Corp','Trust'],
        errorId: 'type_entity_error_id',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'entity_name',
        label: 'Entity name',
        errorId: 'entity_name_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [
            {
                validation: /^(?!.*([A-Za-zñÑáéíóúÁÉÍÓÚ\s])\1{3}).+$/,
                errorText: 'Incluye tu nombre completo, tal como aparece en tu identificación'
            },
            {
                validation: /^[A-Za-z][A-Za-z]*$/,
                errorText: 'Incluye tu nombre completo, tal como aparece en tu identificación'
            }

        ],
        maxLength: 200,
        minLength: 5,
        isRequired: true,
    },
    {
        id: 'signature',
        label: 'Authorized Signature ( First name + Last)',
        errorId: 'signature_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 200,
        minLength: 5,
        isRequired: true,
    },
    {
        id: 'date_bithday',
        label: 'Date Of Birth',
        errorId: 'date_bithday_error',
        placeholder: 'mm/dd/yyyy',
        typeInput: 'DatePicker',
        isRequired: true,
    },
    {
        id: 'tax_id',
        label: 'Tax ID #',
        errorId: 'tax_id_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [], // TODO: Add the ZIP validation
        maxLength: 200,
        minLength: 5,
        isRequired: true,
    },
    {
        id: 'tax_id_document',
        label: 'Tax ID Document',
        errorId: 'tax_id_document_error',
        placeholder: '',
        typeInput: 'FileUpload',
        fileUploaded: null,
        isRequired: true,
    },
    {
        id: 'tax_country',
        label: 'Tax Country',
        options: ['United States', 'Venezuela', 'Colombia', 'Argentina', 'Panama'],
        errorId: 'tax_country_error',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'region_formation',
        label: 'Region of Formation',
        options: ['no idea where search this info',],
        errorId: 'region_formation_error',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'phone_number',
        label: 'Phone Number',
        errorId: 'phone_number_error',
        placeholder: '+54 11-2222-4444',
        typeInput: 'textField',
        type: 'number',
        validationRegex: [
            {
                validation: /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/,
                errorText: 'El telefono ingresado es invalido'
            },
        ],
        maxLength: 200,
        minLength: 5,
        isRequired: true,
    },
    {
        id: 'document_shareholders',
        label: 'Document of list of shareholders',
        errorId: 'document_shareholders_error',
        placeholder: '',
        typeInput: 'FileUpload',
        fileUploaded: null,
        isRequired: true,
    },
    {
        id: 'part?',
        label: 'Everyone who has more that 25% of business uploads Shareholders info ***copy personal info from other form but add two fields: Company role and email Must include proof of ID and Proof of address along with uploads',
        errorId: 'part?',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 200,
        minLength: 2,
        isRequired: true,
    },
    {
        id: 'company_street',
        label: 'Company Street',
        errorId: 'company_street_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 200,
        minLength: 2,
        isRequired: true,
    },
    {
        id: 'company_street_2',
        label: 'Company Street 2',
        errorId: 'company_street_2error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 200,
        minLength: 2,
        isRequired: false,
    },
    {
        id: 'company_country_selection',
        label: 'Company Country',
        options: ['United States', 'Venezuela', 'Colombia', 'Argentina', 'Panama'],
        errorId: 'company_country_error',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'company_state_related_selection',
        label: 'Company State',
        options: ['No idea where find the info yet'],
        errorId: 'company_state_related_error',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'company_city_related',
        label: 'Company City',
        options: ['No idea where find the info yet'],
        errorId: 'Company_city_related_error',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'company_postal_code',
        label: 'Company Postal Code',
        errorId: 'company_postal_code_error',
        placeholder: '',
        typeInput: 'textField',
        validationRegex: [],
        maxLength: 50,
        minLength: 2,
        isRequired: true,
    },
    {
        id: 'document_creation',
        label: 'Document Creation of Business',
        errorId: 'document_creation_error',
        placeholder: '',
        typeInput: 'FileUpload',
        fileUploaded: null,
        isRequired: true,
    },
    {
        id: 'validate_addres_type',
        label: 'Validate address document type',
        options: ['?'],
        errorId: 'validate_addres_type_error',
        placeholder: '',
        typeInput: 'Dropdown',
        isRequired: true,
    },
    {
        id: 'validate_address_document',
        label: 'Validate Address Document',
        errorId: 'validate_address_document_error',
        placeholder: '',
        typeInput: 'FileUpload',
        fileUploaded: null,
        isRequired: true,
    }
]